version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "docker"
    directory: "/grpc"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "docker"
    directory: "/tcp"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "docker"
    directory: "/udp"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"
