version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"

  - package-ecosystem: "pip"
    directory: "/nap-dos"
    schedule:
      interval: weekly
    reviewers:
      - "nginxinc/kic"
