version: 2
env:
  - CGO_ENABLED=0

builds:
  - main: ./tcp/
    binary: "main"
    id: "tcp"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  - main: ./udp/
    binary: "main"
    id: "udp"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

changelog:
  disable: true
