name: Lint

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Golang Environment
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1 # renovate: datasource=github-tags depName=golangci/golangci-lint

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -shellcheck ""
